# -*- coding: utf-8 -*-
"""BN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3oMuXTyKnqUFk1f82yEBW_46APd6voN
"""

from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import warnings
from torchvision import datasets, transforms
warnings.filterwarnings("ignore")

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        drop_out_val = 0.05 # 0.05
        self.convblock1 = nn.Sequential(
            nn.Conv2d(in_channels=1, out_channels=8, kernel_size=(3, 3), padding=1, bias=False),
            nn.ReLU(),
            nn.BatchNorm2d(8),
            nn.Dropout(p=drop_out_val)
        ) # output_size = 28, rc-3

        self.convblock2 = nn.Sequential(
            nn.Conv2d(in_channels=8, out_channels=8, kernel_size=(3, 3), padding=1, bias=False),
            nn.ReLU(),
            nn.BatchNorm2d(8),
            nn.Dropout(p=drop_out_val)
        ) # output_size = 28, rc-5

        self.pool1 = nn.MaxPool2d(2, 2) # output_size = 12

        self.convblock3 = nn.Sequential(
            nn.Conv2d(in_channels=8, out_channels=16, kernel_size=(3, 3), padding=1, bias=False),
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Dropout(p=drop_out_val)
        ) # output_size = 28

        self.convblock4 = nn.Sequential(
            nn.Conv2d(in_channels=16, out_channels=16, kernel_size=(3, 3), padding=1, bias=False),
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Dropout(p=drop_out_val)
        ) # output_size = 28

        self.pool2 = nn.MaxPool2d(2, 2) # output_size = 14
        self.convblock100 = nn.Sequential(
            nn.Conv2d(in_channels=16, out_channels=8, kernel_size=(1, 1), padding=0, bias=False),
            # nn.ReLU(),
            # nn.Dropout(p=drop_out_val)
        ) # output_size = 14

        self.convblock5 = nn.Sequential(
            nn.Conv2d(in_channels=8, out_channels=16, kernel_size=(3, 3), padding=0, bias=False),
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Dropout(p=drop_out_val)
        ) # output_size = 12

        self.convblock6 = nn.Sequential(
            nn.Conv2d(in_channels=16, out_channels=16, kernel_size=(3, 3), padding=0, bias=False),
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Dropout(p=drop_out_val)
        ) # output_size = 10

        self.gap = nn.Sequential(nn.AvgPool2d(3)) # output_size = 1
        self.fc = nn.Linear(16, 10)  # 1*1*32 | 10


    def forward(self, x):
        # Adding drop out reduces the accuracy a bit
        x = self.convblock1(x)
        x = self.convblock2(x)
        x = self.pool1(x)
        x = self.convblock3(x)
        x = self.convblock4(x)
        x = self.pool2(x)
        x = self.convblock100(x)
        x = self.convblock5(x)
        x = self.convblock6(x)
        x = self.gap(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return F.log_softmax(x)